Docbug/eks cluster with vpc ref tag
aws-observability/terraform-aws-observability-accelerator pull request #121
Opened 2023-02-18 02:16 UTC by luiscamaral

### What does this PR do?

Fix reference link on example docs.  (#120)

### Motivation

Broken reference links not pointing to a valid address. (_broken link_)

### More

- [ ] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

#### [Add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) project was checked and no references was found

![image](https://user-images.githubusercontent.com/3392839/219826490-8d20c8c1-9203-46f9-9d1a-6174be649195.png)

2023-02-18 20:07 UTC, bonclay7 requested changes
Thanks so much for adressing that, can you please fix the numbers on the nginx doc?

2023-02-18 20:07 UTC, bonclay7 commented on examples/existing-cluster-nginx/README.md
> -5. Amazon Managed Service for Prometheus workspace (optional)
Can you keep the number five for this?

2023-02-19 01:49 UTC, luiscamaral commented on examples/existing-cluster-nginx/README.md
> -5. Amazon Managed Service for Prometheus workspace (optional)
oops... not sure how it happened.

2023-02-19 10:15 UTC, bonclay7 submitted a review, later dismissed

2023-02-19 10:18 UTC, bonclay7 commented
@luiscamaral there's one other place where we have this link as well `docs/helpers/new-eks-cluster.md`. while you're at it could you please fix?

2023-02-19 20:30 UTC, luiscamaral commented
Found yet another link missing the version and fixed it

[`./docs/helpers/new-eks-cluster.md:4:...`](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/v1.6.3/docs/helpers/new-eks-cluster.md)

2023-02-19 21:19 UTC, bonclay7 approved these changes

2023-02-19 21:19 UTC, merged

2023-02-19 21:20 UTC, bonclay7 commented
Thanks a lot @luiscamaral