Checking in Istio example
aws-observability/terraform-aws-observability-accelerator pull request #181
Opened 2023-06-12 21:58 UTC by preddy727

### What does this PR do?

Checking in Istio example with tetrate using EKS blueprint, adot and sending istio metrics to prometheus for grafana visualization 

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted. Consult the CONTRIBUTING guide for submitting pull-requests.

### Motivation

### More

- [x ] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [ x] Yes, I ran `pre-commit run -a` with this PR
- [ x] Yes, I have added a new example under [examples](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples) to support my PR (when applicable)
- [ x] Yes, I have updated the [Pages](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/docs) for this feature

**Note**: Not all the PRs required examples and docs.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

2023-06-15 08:35 UTC, bonclay7 requested changes
Thanks a lot for this awesome, unfortunately this PR came in between a change in structure, so you will have to change a few stuff. Let me know if you need any help with this

2023-06-15 08:35 UTC, bonclay7 commented on modules/eks-monitoring/patterns/istio/dashboards/istio-control-plane-dashboard.json
With Grafana operator managing the dashboards with GitOps, we moved all the dashboards [here](https://github.com/aws-observability/aws-observability-accelerator/tree/main/artifacts/grafana-dashboards/eks)
Please create a new directory for istio and add the dashboards there. Also, set the dashbaord `id` to `null`

2023-06-15 08:35 UTC, bonclay7 commented on modules/eks-monitoring/patterns/istio/main.tf
> +*/
You can delete this if this is not needed anymore

2023-06-15 08:35 UTC, bonclay7 commented on modules/eks-monitoring/patterns/istio/main.tf
> +
Move these to [Flux provisioning](https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/patterns/java/main.tf#L35-L58) instead

2023-06-15 08:35 UTC, bonclay7 commented on modules/eks-monitoring/patterns/istio/outputs.tf
> +output "grafana_dashboard_urls" {
We won't have the outputs anymore :(

2023-06-15 08:35 UTC, bonclay7 commented on modules/eks-monitoring/patterns/istio/variables.tf
> +variable "enable_alerting_rules" {
Patterns have now have config objects 
- pattern variable https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/patterns/java/variables.tf#L1-L26 and 
- eks module declaration https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/variables.tf#L248-L270, customers can change these entirely
- we compute default values in locals https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/locals.tf#L33-L55
- and we evaluate if customer provided something, else we use the defaults https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/modules/eks-monitoring/main.tf#L190

2023-06-15 08:35 UTC, bonclay7 commented on modules/eks-monitoring/patterns/istio/versions.tf
> +    }
Provider not needed anymore

2023-06-19 14:49 UTC, bonclay7 commented
@awsdabra @preddy727 let me know if you need any help!

2023-06-22 21:04 UTC, preddy727 commented on examples/existing-cluster-istio-monitoring/README.md
Renamed example folder to eks-istio.

2023-06-26 15:23 UTC, closed without merging

2023-06-28 02:36 UTC, preddy727 commented on examples/existing-cluster-istio-monitoring/README.md
> +## Prerequisites
Moved detailed instructions to Github pages.   Added a page for Istio and also defined that new file.

2023-06-28 02:38 UTC, preddy727 commented on examples/existing-cluster-istio-monitoring/README.md
> +You can improve security and performance by creating VPC-endpoint for Amazon Managed Service for Prometheus. For more information, see Using Amazon Service for Prometheus with interface VPC endpoints
Took this step out.

2023-06-28 03:10 UTC, preddy727 commented on examples/existing-cluster-istio-monitoring/README.md
> +## Prerequisites
Updated github pages.

2023-06-28 03:11 UTC, preddy727 commented on examples/existing-cluster-istio-monitoring/README.md
> +7. [Grafana api key with Admin role](https://docs.aws.amazon.com/grafana/latest/userguide/API_key_console.html)
Done.

2023-06-28 03:13 UTC, preddy727 commented on examples/existing-cluster-istio-monitoring/README.md
> +3. Update variables.tf. Uncomment each of the defaults below with actual values for the name of the EKS cluster, aws_region, Prometheus workspace id, grafana workspace id and grafana api key.
Removed from readme and updated examples

2023-06-28 07:48 UTC, bonclay7 commented
@preddy727 I don't understand why you closed the PR