EKS Cross Cluster Observability using central AMP
aws-observability/terraform-aws-observability-accelerator pull request #213
Opened 2023-08-10 03:41 UTC by veekaly

### What does this PR do?

This provides updates to the `eks-monitoring` module to allow ADOT to perform cross-account metric streaming to cross account AMP. 

It also provides an example to deploy `eks-monitoring` module to setup EKS observability across clusters in multiple accounts to integrate with cross-account AMP and deploy grafana dashboards to cross-account AMG.

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted. Consult the CONTRIBUTING guide for submitting pull-requests.

### Motivation

### More

- [x] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [x] Yes, I ran `pre-commit run -a` with this PR
- [x] Yes, I have added a new example under [examples](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples) to support my PR (when applicable)
- [x] Yes, I have updated the [Pages](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/docs) for this feature

**Note**: Not all the PRs required examples and docs.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

2023-08-16 13:48 UTC, bonclay7 commented on examples/eks-cross-account-with-central-amp/README.md
Can you move the docs to the [docs site](https://aws-observability.github.io/terraform-aws-observability-accelerator/), under Amazon EKS?  This helps communicating on new changes with a user-friendly UI. 

The contribution guide can be found [here](https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/CONTRIBUTING.md#documentation-with-mkdocs)

2023-08-16 13:49 UTC, bonclay7 commented on examples/eks-cross-account-with-central-amp/README.md
You can how other examples do 
https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples/eks-container-insights

2023-08-16 14:06 UTC, veekaly commented on examples/eks-cross-account-with-central-amp/README.md
Will make those changes and update the PR by EOD

2023-08-16 14:18 UTC, lewinkedrs requested changes
This looks good to me. Let's fix the readmes by removing the admonitions and then try adding a variable for AMP workspace and we should be good to go.

2023-08-16 14:18 UTC, lewinkedrs commented on examples/eks-cross-account-with-central-amp/README.md
> +!!! note
These markdown admonitions '!!! note' only need to go in the docs markdown. Not the readme. I don't believe they do anything here in the github markdown.

2023-08-16 14:18 UTC, lewinkedrs commented on examples/eks-cross-account-with-central-amp/main.tf
> +  amp_workspace_alias = "aws-observability-accelerator"
should this instead be a variable in case the customer wants to use their own amp workspace. You can have the default be "aws-observability-accelerator".

2023-08-16 17:47 UTC, lewinkedrs commented on examples/eks-cross-account-with-central-amp/README.md
> +!!! note
Yes let's do that. Looks good to me.

2023-08-29 10:25 UTC, bonclay7 commented
@veekaly can you send a fix for those comments please?

2023-09-01 13:40 UTC, veekaly commented on examples/eks-cross-account-with-central-amp/README.md
Changed updated to the fork

2023-09-01 13:40 UTC, veekaly commented on examples/eks-cross-account-with-central-amp/README.md
> +!!! note
Changes updated to the fork

2023-09-01 13:42 UTC, veekaly commented on examples/eks-cross-account-with-central-amp/main.tf
> +  amp_workspace_alias = "aws-observability-accelerator"
Change updated in the fork

2023-09-01 13:53 UTC, veekaly commented
> @veekaly can you send a fix for those comments please?

Requested changes have been made. Please let me know if any further changes required. Thanks!

2023-09-01 15:03 UTC, bonclay7 requested changes
just teeny tiny changes

2023-09-01 16:14 UTC, veekaly commented on examples/eks-cross-account-with-central-amp/iam.tf
> +resource "aws_iam_role_policy_attachment" "role-attach" {
Made the changes to the fork

2023-09-01 16:34 UTC, bonclay7 approved these changes
Looks good! thanks @veekaly

2023-09-01 16:55 UTC, lewinkedrs approved these changes
LGTM!

2023-09-01 16:55 UTC, merged