API Key rotation for Grafana Workspace
aws-observability/terraform-aws-observability-accelerator pull request #259
Opened 2024-01-17 21:30 UTC by veerapratapg

### What does this PR do?

- Added a module to enable Grafana API Key rotation --> [grafana-key-rotation](https://github.com/veerapratapg/terraform-aws-observability-accelerator/tree/main/modules/grafana-key-rotation) 
- Made appropriate changes to the [eks-monitoring](https://github.com/veerapratapg/terraform-aws-observability-accelerator/tree/main/modules/eks-monitoring) module to retrieve the details of the resources created in the in this module to be used for the above key rotation module. 
- Modified the [existing-cluster-with-base-and-infra](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples/existing-cluster-with-base-and-infra) example to create create the grafana-key-rotation module. 

### Motivation

- The current _[existing-cluster-with-base-and-infra](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples/existing-cluster-with-base-and-infra)_ example does not rotate the expired Grafana Workspace API keys automatically. 
- Modifying the example to enable key rotation for External Secrets deployed to the EKS Cluster as part of this solution. 
- Steps provided in https://docs.aws.amazon.com/prometheus/latest/userguide/obs_accelerator.html

### More

- [X] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [X] Yes, I ran `pre-commit run -a` with this PR
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples) to support my PR (when applicable)
- [ ] Yes, I have updated the [Pages](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/docs) for this feature

**Note**: Not all the PRs required examples and docs.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

2024-01-17 21:42 UTC, veerapratapg commented
Tagging reviewers --> @bonclay7 @lewinkedrs

2024-01-18 17:31 UTC, lewinkedrs reviewed
Looks good to me but I did leave some comments with a few small fixes. We also need a doc for this. Can you write a markdown file in the docs folder describing how to use this module? Do not worry about the folder structure or where in the website to place the doc, we can do that part. But in the doc give a brief intro to what this module does, how to enable it or disable it, and describe some of the configuration options available to the users. Thank you for the contribution though it is looking very nice!

2024-01-18 17:31 UTC, lewinkedrs commented on modules/grafana-key-rotation/main.tf
> +  runtime       = "python3.8"
3.8 has a deprecation date of this year already. Can you test if this works properly with one of the newer run times? This way we don't have to worry about bumping the version later when it is deprecated.

2024-01-18 17:31 UTC, lewinkedrs commented on modules/grafana-key-rotation/main.tf
> +  name       = "test-attachment"
can we name this something other than 'test-attachment' . Having the word 'test' in there makes it sound unfinished. Maybe call it like "policy-attachment"

2024-01-18 17:31 UTC, lewinkedrs commented on modules/grafana-key-rotation/main.tf
> +
remove blank whitespace line

2024-01-18 17:31 UTC, lewinkedrs commented on modules/grafana-key-rotation/main.tf
> +
remove blank whitespace line

2024-01-18 17:31 UTC, lewinkedrs commented on modules/grafana-key-rotation/main.tf
> +  name       = "test-attachment"
as before, let's not use the name 'test-attachment'

2024-01-31 04:35 UTC, veerapratapg commented
Made the following changes to incorporate the suggestions from @lewinkedrs :
1. Added a README.md doc to grafana-key-rotation module with the requested information. 
2. Performed testing with the latest version of python runtime for Lambda, "3.12", and the solution is working as expected. 
3. Removed `test` from the names of policy attachment resources. 
4. Also removed white spaces from the mentioned files. 
5. Added variables for python runtime, event bridge scheduler expressions to provide additional flexibility for users.

2024-01-31 21:42 UTC, lewinkedrs approved these changes
LGTM

2024-01-31 22:00 UTC, bonclay7 requested changes
Can you please address this change, re-run pre-commit, and test it once more, as I've fixed some conflicts in your branch. 
Thanks again for the work!

2024-02-06 05:58 UTC, veerapratapg commented
Made the changes suggested by @bonclay7 and removed `managed_grafana_workspace_id` from the SSM parameter name created through `external-secrets` to reduce the number of changes made.

2024-02-06 17:31 UTC, veerapratapg commented on modules/eks-monitoring/outputs.tf
> +}
Made the suggested change and removed `_eks_monitoring` from output names.

2024-06-18 05:46 UTC, veerapratapg commented
Added Unit Tests for Lambda function in the `grafana-key-rotation` module in the directory `./modules/grafana-key-rotation/tests/unit/src`. Also added a ReadMe file in the same location with a quick overview of steps to run the Tests.

2024-08-26 21:24 UTC, closed without merging

2024-08-26 21:28 UTC, veerapratapg commented
Closing this PR as Managed Grafana v9 and 10 introduced Service account and service account token (SAT) APIs, instead of API Keys.