Feature/enable polyglot otel config
aws-observability/terraform-aws-observability-accelerator pull request #287
Opened 2024-10-25 17:37 UTC by hmuthusamy

### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted. Consult the CONTRIBUTING guide for submitting pull-requests.
Fix for nginx and java monitoring dashboards on EKS failing because of race condition deploying dashboards first before flux is deployed.
Also added polyglot monitoring for Rust,.Net monitoring using OTEL.

### Motivation

### More

- [ Yes] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [Yes ] Yes, I ran `pre-commit run -a` with this PR
- [ Yes] Yes, I have added a new example under [examples](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples) to support my PR (when applicable)
- [ Yes] Yes, I have updated the [Pages](https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/docs) for this feature

**Note**: Not all the PRs required examples and docs.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

2024-10-25 21:26 UTC, elamaran11 approved these changes
LGTM. This works great and tested. @bonclay7 Can you review and merge it. Need for RI Setup.

2024-10-28 11:01 UTC, bonclay7 requested changes
Looks good but tests are failing. Can you run pre-commit and commit changes @hmuthusamy 
https://github.com/aws-observability/terraform-aws-observability-accelerator/actions/runs/11522847911/job/32088304356?pr=287

2024-10-28 13:21 UTC, hmuthusamy commented
> Looks good but tests are failing. Can you run pre-commit and commit changes @hmuthusamy https://github.com/aws-observability/terraform-aws-observability-accelerator/actions/runs/11522847911/job/32088304356?pr=287

@bonclay7 Ran the pre-commit and submitted for review. Please review and merge. Thanks

2024-10-28 14:40 UTC, elamaran11 commented
@hmuthusamy Precommit is failing still. Lets fix it.

2024-10-28 19:21 UTC, bonclay7 commented on modules/eks-monitoring/otel-config/templates/opentelemetrycollector.yaml
> +                - role: pod
This seems a bit wide, as without any relabel config or port capture, it would capture any exposed metrics at the pod level unless i'm missing something. Can you make it more specific to what you are collecting?

2024-10-28 19:22 UTC, bonclay7 commented
Fixed the tests, but I have one concern @hmuthusamy 
FYI - @lewinkedrs

2024-10-28 22:31 UTC, hmuthusamy commented on modules/eks-monitoring/otel-config/templates/opentelemetrycollector.yaml
> +                - role: pod
@bonclay7  Happy to discuss this on a call. We are going to setup .net, Rust,Go and other dashboards as part of the RI workshop. We opened up all the pods (defaulted to false and only explicitly set to true) for the usecase. Once we finalize all the metrics for all these languages/apps and understand what filters we need to apply we will apply them along with corresponding dashboards similar to how its implemented for Java.

2024-10-29 16:46 UTC, elamaran11 commented
@bonclay7 Pls merge this or let us know if you have questions. This is blocker for RI. We are having enable for polyglot flag so pod level metrics isnt going to be a problem. This flag willbe disabled by default

2024-10-30 21:02 UTC, closed without merging