Nginx module source
aws-observability/terraform-aws-observability-accelerator pull request #35
Opened 2022-09-19 13:09 UTC by lewinkedrs

### What does this PR do?

Adds an NGINX example of the observability accelerator with dashboard and alerting rules. https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/22

### Motivation

NGINX is a common workload on EKS. This PR is an attempt to give users the ability to easily create a dashboard and alerting rules to gain observability.

### More

- [*] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [*] Yes, I have added a new example under [examples](https://github.com/aws-observability/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [n/a ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [n/a] Yes, I have updated the [docs](https://github.com/aws-observability/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

2022-09-21 18:50 UTC, bonclay7 requested changes
Thanks @lewinkedrs! Few things to cleanup

2022-09-21 18:50 UTC, bonclay7 commented on examples/existing-cluster-nginx/README.md
> +7. Grafana API Key
For this section, can you look at the latest changes on the infra example. We should avoid storing api keys in tfvars files

2022-09-21 18:50 UTC, bonclay7 commented on examples/existing-cluster-nginx/README.md
> +## Visualization
Maybe can we add a section on how to verify if it works with some `kubectl` commands output?

2022-09-21 18:50 UTC, bonclay7 commented on examples/existing-cluster-nginx/README.md
> +4. Set an EXTERNAL-IP variable to the value of the EXTERNAL-IP column in the row of the NGINX ingress controller.
So I think this doc is from the Containers Insights, and there's a step missing (step 3)

https://docs.amazonaws.cn/en_us/AmazonCloudWatch/latest/monitoring/ContainerInsights-Prometheus-Sample-Workloads-nginx.html

I'm actually unable to have any `ingress` label attached to my metrics, maybe I'm missing something?

2022-09-21 18:50 UTC, bonclay7 commented on examples/existing-cluster-nginx/main.tf
> +
can you put it a `versions.tf` file? We will use it for CI/CD
ex: https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/examples/existing-cluster-with-base-and-infra/versions.tf

2022-09-21 18:50 UTC, bonclay7 commented on examples/existing-cluster-nginx/main.tf
> +//*
can you drop the comments?

2022-09-21 18:50 UTC, bonclay7 commented on examples/existing-cluster-nginx/main.tf
> +//*/
here too

2022-09-21 18:50 UTC, bonclay7 commented on modules/workloads/nginx/variables.tf
> +    ne_helm_values        = map(any)
I think you don't need those

2022-09-21 18:50 UTC, bonclay7 commented on modules/workloads/nginx/variables.tf
> +    enable_node_exporter      = true
don't need this

2022-09-21 18:50 UTC, bonclay7 commented on modules/workloads/nginx/variables.tf
> +    ne_helm_values        = {}
don't need this

2022-09-21 18:50 UTC, bonclay7 commented on modules/workloads/nginx/variables.tf
> +}
drop those unused variables

2022-09-21 18:52 UTC, bonclay7 commented
Linked to https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/22

2022-09-22 14:54 UTC, lewinkedrs commented on examples/existing-cluster-nginx/README.md
> +7. Grafana API Key
Resolved. Moved to setting env variable via aws cli command.

2022-09-22 15:01 UTC, lewinkedrs commented on examples/existing-cluster-nginx/README.md
> +## Visualization
Added:

Confirm the ADOT operator and collector were deployed

```sh
kubectl get pods -A | grep 'collector\|operator'
```

2022-09-22 15:04 UTC, lewinkedrs commented on examples/existing-cluster-nginx/README.md
> +4. Set an EXTERNAL-IP variable to the value of the EXTERNAL-IP column in the row of the NGINX ingress controller.
Added the missing step here. I think this actually fails though on newer versions of kubernetes. I will need to go back and investigate this deeper and maybe use a different sample deployment that works on newer versions of the kubernetes api.

2022-09-22 15:09 UTC, lewinkedrs commented on examples/existing-cluster-nginx/main.tf
> +
Added versions.tf and removed from main.tf

2022-09-22 15:09 UTC, lewinkedrs commented on examples/existing-cluster-nginx/main.tf
> +//*
dropped.

2022-09-22 15:13 UTC, lewinkedrs commented on modules/workloads/nginx/variables.tf
> +    ne_helm_values        = map(any)
Removed the variable and switched the namespace to just be local.name instead of trying the helm config.

2022-09-23 15:56 UTC, bonclay7 approved these changes
Awesome, let's check pre-commit

2022-09-26 15:54 UTC, awsvikram approved these changes

2022-09-27 14:00 UTC, merged