AMP Observability Pattern
aws-observability/terraform-aws-observability-accelerator pull request #55
Opened 2022-10-19 16:39 UTC by lewinkedrs

### What does this PR do?

This PR provides an AMP observability pattern (module and example) to give customers insights into their AMP usage and spend.

Fixes issue #30 

### Motivation

Customers using the accelerator should have a module that provides insight and observability over the AMP deployment itself. This should not depend on any metrics within AMP itself.

### More

- [X] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [X] Yes, I have added a new example under [examples](https://github.com/aws-observability/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-observability/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [X] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

2022-10-25 16:34 UTC, bonclay7 requested changes
Let's start the discussion with these and thanks for this!

2022-10-25 16:34 UTC, bonclay7 commented on examples/amp-monitoring/variables.tf
> +variable "enable_managed_grafana" {
I think we should remove this for now. MG creation is not that straightforward. Or at least we should default it to false

2022-10-25 16:34 UTC, bonclay7 commented on examples/amp-monitoring/versions.tf
> +  required_version = ">= 1.1.0, < 1.3.0"
`required_version = ">= 1.1.0"`

2022-10-25 16:34 UTC, bonclay7 commented on examples/amp-monitoring/main.tf
> +    resource.grafana_folder.this
please run `terraform fmt` or run `pre-commit run -a` locally

2022-10-25 16:34 UTC, bonclay7 commented on examples/amp-monitoring/main.tf
> +  count   = var.enable_managed_grafana ? 1 : 0
oh so you create a workspace and data source here. Why not extend the datasource config in the base module?
Examples should not have the main logic imo

2022-10-25 16:34 UTC, bonclay7 commented on examples/amp-monitoring/main.tf
> +    aws = aws.billing_region
nice! This is the concept i was talking to you about. we have to extend it to AMP and MG to support x-region

2022-10-25 16:34 UTC, bonclay7 commented on examples/amp-monitoring/README.md
> +Open the `AMP Accelerator Dashboard` to see a visualization of the AMP workspace.
If we move that to the base module we can reuse the same folder `Observability Accelerator Dashboards`

2022-10-25 16:34 UTC, bonclay7 commented on modules/billing/main.tf
> +      period      = "21600"
We should make variables with default values and allow customers to change them

2022-10-25 16:34 UTC, bonclay7 commented on modules/billing/main.tf
> +        Currencty = "USD"
typo on "Currencty"

2022-10-25 16:34 UTC, bonclay7 commented on modules/billing/versions.tf
> +  required_version = ">= 1.1.0, < 1.3.0"
`required_version = ">= 1.1.0"`

2022-10-25 16:34 UTC, bonclay7 commented on modules/workloads/amp-monitoring/alarms.tf
> +      period      = "120"
Let's define variables and default values

2022-10-25 16:34 UTC, bonclay7 commented on modules/workloads/amp-monitoring/alarms.tf
> +      period      = "120"
Let's define variables and default values

2022-10-25 16:34 UTC, bonclay7 commented on modules/workloads/amp-monitoring/versions.tf
> +  required_version = ">= 1.1.0, < 1.3.0"
`required_version = ">= 1.1.0"`

2022-11-07 20:47 UTC, bonclay7 commented
@lewinkedrs can you check the pre-commit errors on github actions? There are few variables not necessary.

2022-12-06 20:48 UTC, lewinkedrs reviewed
Resolved 1 and 3 with recent commit. We will discuss how to implement 2 .

2022-12-09 12:39 UTC, bonclay7 approved these changes
Thanks @lewinkedrs! Feel free to squash and merge

2022-12-09 15:49 UTC, merged

2023-05-15 14:27 UTC, jeromeinsf commented on modules/workloads/managed-prometheus-monitoring/main.tf
> +    sigv4_auth_type = "workspace-iam-role"
Are you sure this works?
According to https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#allowed_auth_providers the expected value should be `ec2_iam_role`