Managed Grafana Workspace with Identity Centre Users
aws-observability/terraform-aws-observability-accelerator pull request #83
Opened 2023-01-20 16:32 UTC by charliekeeegan

### What does this PR do?

Creates AWS Identity Center users from given variables (first name, last name, email) which are then associated to a new Amazon Managed Grafana workspace as Admins. 

An Admin API key with TTL of 3 days is also created and used as an output. 

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted. Consult the CONTRIBUTING guide for submitting pull-requests.

### Motivation

https://github.com/aws-observability/terraform-aws-observability-accelerator/issues/48

### More

- [x] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [x] Yes, I have added a new example under [examples](https://github.com/aws-observability/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-observability/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

2023-01-23 20:17 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +data "aws_ssoadmin_instances" "example" {}
I think we need to have a variable to provide identity store id. We could use locals, something like that https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/locals.tf#L22

2023-01-23 20:17 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +  identity_store_id = tolist(data.aws_ssoadmin_instances.example.identity_store_ids)[0]
rely on locals to have a fallback

2023-01-23 20:18 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +data "aws_ssoadmin_instances" "example" {}
for consistency, can you please use `this` instead of `example`?

2023-01-23 20:18 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +resource "aws_identitystore_user" "example" {
same here `this`

2023-01-23 20:19 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +resource "aws_grafana_workspace" "workshop" {
`this`

2023-01-23 20:21 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +  name                     = "eks-observability-workshop-workspace"
I would suggest for consistency use `aws-observability-accelerator` by default, but provide a variable so users can optionally name it differently

2023-01-23 20:22 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +  description              = "EKS Observability Workshop's Grafana Workspace"
naming's `AWS Observability Accelerator`

2023-01-23 20:23 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +resource "aws_iam_role" "assume" {
`this`

2023-01-23 20:24 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +  name = "eks-observability-accelerator-grafana-assume"
`aws-observability-accelerator-grafana`

2023-01-23 20:25 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +  role_arn                 = aws_iam_role.assume.arn
I think the role needs to have at least Amazon Managed Service for Prometheus read-only permissions

2023-01-23 20:26 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +resource "aws_grafana_workspace_api_key" "key" {
`this`

2023-01-23 20:28 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +  seconds_to_live = 259200 #3 days
I think we shouldn't create an API key with this module. 
1/ 3 days is not something we recommend
2/ If a customer is using this module just to deploy grafana, this might not make sense
3/ On the other examples, when we need grafana api keys, we give a CLI commend that generates 30 min lived api keys

2023-01-23 20:28 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +resource "aws_grafana_role_association" "example" {
`this`

2023-01-23 20:29 UTC, bonclay7 commented on examples/managed-grafana-setup/outputs.tf
> +output "grafana-workspace-api-key" {
as above, this doesn't meet our security recommendations

2023-01-23 20:29 UTC, bonclay7 commented on examples/managed-grafana-setup/outputs.tf
> +output "grafana-workspace-endpoint" {
naming convention should be '_`
https://www.terraform-best-practices.com/naming

2023-01-23 20:35 UTC, bonclay7 commented on examples/managed-grafana-setup/readme.md
> +# Deployment Instructions
I think the README should be a bit expanded to showcase a deployment example with this and explain the limitations, such as the regions requirements. 
take a look at: https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/examples/eks-cluster-with-vpc

Also, we'll need to add a doc here https://github.com/aws-observability/terraform-aws-observability-accelerator/tree/main/docs/helpers. Think of it as a mini blog post for what you added. Maybe in another PR

And if you add these comments below and run pre-commit, you will get auto-generated Terraform docs.
```
<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
```

2023-01-23 22:18 UTC, charliekeeegan commented on examples/managed-grafana-setup/main.tf
> +data "aws_ssoadmin_instances" "example" {}
done

2023-01-23 22:18 UTC, charliekeeegan commented on examples/managed-grafana-setup/main.tf
> +data "aws_ssoadmin_instances" "example" {}
done

2023-01-23 22:19 UTC, charliekeeegan commented on examples/managed-grafana-setup/main.tf
> +data "aws_ssoadmin_instances" "example" {}
done

2023-01-23 22:20 UTC, charliekeeegan commented on examples/managed-grafana-setup/outputs.tf
> +output "grafana-workspace-api-key" {
done

2023-01-23 22:20 UTC, charliekeeegan commented on examples/managed-grafana-setup/outputs.tf
> +output "grafana-workspace-endpoint" {
done

2023-01-23 22:28 UTC, charliekeeegan commented on examples/managed-grafana-setup/main.tf
> +  identity_store_id = tolist(data.aws_ssoadmin_instances.example.identity_store_ids)[0]
can you explain this further?

2023-01-23 22:29 UTC, charliekeeegan commented on examples/managed-grafana-setup/main.tf
> +resource "aws_grafana_workspace" "workshop" {
done

2023-01-23 22:30 UTC, charliekeeegan commented on examples/managed-grafana-setup/main.tf
> +  name                     = "eks-observability-workshop-workspace"
done

2023-01-23 22:30 UTC, charliekeeegan commented on examples/managed-grafana-setup/main.tf
> +  description              = "EKS Observability Workshop's Grafana Workspace"
done

2023-01-23 22:30 UTC, charliekeeegan commented on examples/managed-grafana-setup/main.tf
> +resource "aws_iam_role" "assume" {
done

2023-01-23 22:31 UTC, charliekeeegan commented on examples/managed-grafana-setup/main.tf
> +  name = "eks-observability-accelerator-grafana-assume"
done

2023-01-23 22:32 UTC, charliekeeegan commented on examples/managed-grafana-setup/main.tf
> +resource "aws_grafana_role_association" "example" {
done

2023-01-24 10:31 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +  identity_store_id = tolist(data.aws_ssoadmin_instances.example.identity_store_ids)[0]
I meant build this list in a local variable where you can take a user variable as in put and falling back you can use the data source

ex: https://github.com/aws-observability/terraform-aws-observability-accelerator/blob/main/locals.tf#L22

2023-01-24 20:11 UTC, bonclay7 requested changes
Just a few bits

2023-01-24 20:11 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +  name                     = "aws-observability-accelerator-workshop-workspace"
So the variable `var.grafana_workspace_name` should be use here I guess?

2023-01-24 20:11 UTC, bonclay7 commented on examples/managed-grafana-setup/main.tf
> +  description              = "AWS Observability Accelerator Workshop's Grafana Workspace"
It's not a workshop, you can drop that word

2023-01-24 20:11 UTC, bonclay7 commented on examples/managed-grafana-setup/readme.md
> +This example created a Managed Grafana Workspace and Identity Centre Users for it.
creates?

2023-01-24 20:11 UTC, bonclay7 commented on examples/managed-grafana-setup/readme.md
> +# Deployment Instructions
I think this should expand to actually show how to do it. Explain the deployment process with text and code. Add examples, and screenshots if possible

2023-01-27 18:29 UTC, merged